group=com.esotericsoftware.spine
version=4.3.0-SNAPSHOT
libgdx_version=1.14.1-SNAPSHOT
POM_NAME=spine-libgdx
POM_DESCRIPTION=Spine Runtime for libGDX
POM_URL=https://github.com/esotericsoftware/spine-runtimes
POM_SCM_URL=https://github.com/esotericsoftware/spine-runtimes
POM_SCM_CONNECTION=scm:git@github.com:esotericsoftware/spine-runtimes.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:esotericsoftware/spine-runtimes.git
POM_LICENCE_NAME=Spine Runtimes License
POM_LICENCE_URL=https://esotericsoftware.com/spine-runtimes-license
POM_LICENCE_DIST=repo