name: Build spine-godot GDExtension (All Godot 4.x versions)

on:
  push:
    branches:
      - '**'
    paths:
      - ".github/workflows/spine-godot-extension-v4-all.yml"
      - ".github/workflows/spine-godot-extension-v4.yml"
      - 'spine-godot/**'
      - 'spine-cpp/**'
  workflow_dispatch:

jobs:
  build-versions:
    strategy:
      matrix:
        version:
          [
            {"tag": "4.6.3-stable", "version": "4.6.3.stable", "api_version": "4.6", "dev": false},
            {"tag": "4.7.2-stable", "version": "4.7.2.stable", "api_version": "4.7", "dev": false},
          ]
    uses: ./.github/workflows/spine-godot-extension-v4.yml
    with:
      godot_tag: ${{ matrix.version.tag }}
      godot_version: ${{ matrix.version.version }}
      godot_cpp_api_version: ${{ matrix.version.api_version }}
      dev: ${{ matrix.version.dev }}
    secrets: inherit
