name: Build spine-ts

on:
  push:
    paths:
      - 'spine-ts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup TypeScript
      uses: actions/setup-node@v3
      with:
        node-version: '16'    
    - name: Build spine-ts
      working-directory: spine-ts
      env:
        TS_UPDATE_URL: ${{secrets.TS_UPDATE_URL}}
      run: ./build.sh