name: Build spine-godot (All Godot 4.x versions)

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/**"
      - "spine-godot/**"
      - "spine-cpp/**"

jobs:
  build-versions:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: "4.5-stable"
            version: "4.5.stable"
            dev: false
          - tag: "4.4.1-stable"
            version: "4.4.1.stable"
            dev: false
          - tag: "4.3-stable"
            version: "4.3.stable"
            dev: false
    uses: ./.github/workflows/spine-godot-v4.yml
    with:
      godot_tag:     ${{ matrix.tag }}
      godot_version: ${{ matrix.version }}
      dev:           ${{ matrix.dev }}
      godot_mono:    false
    secrets: inherit
